# Generated by Django 5.1.5 on 2025-03-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinerecommendation",
            name="medicine_recommendations",
        ),
        migrations.AddField(
            model_name="medicinerecommendation",
            name="medicine",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicines.medicine",
            ),
            preserve_default=False,
        ),
    ]
