# Generated by Django 5.1.5 on 2025-03-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicines",
            "0002_remove_medicinerecommendation_medicine_recommendations_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinerecommendation",
            name="evidence_level",
        ),
        migrations.RemoveField(
            model_name="medicinerecommendation",
            name="recommendation_type",
        ),
    ]
