# Generated by Django 5.1.5 on 2025-03-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("appointments", "0001_initial"),
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHealthDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("addictions", models.TextField(blank=True, null=True)),
                (
                    "diet",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("VEG", "Vegetarian"),
                            ("NON_VEG", "Non-vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("OTHER", "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("comorbidities", models.TextField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "heart_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "rr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "spo2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rs", models.CharField(blank=True, max_length=20, null=True)),
                ("cvs", models.CharField(blank=True, max_length=20, null=True)),
                ("p_a", models.CharField(blank=True, max_length=20, null=True)),
                ("cns", models.CharField(blank=True, max_length=20, null=True)),
                ("presenting_complaints", models.TextField(blank=True, null=True)),
                ("provisional_diagnosis", models.TextField(blank=True, null=True)),
                ("investigation_advice", models.TextField(blank=True, null=True)),
                ("diet_advice", models.TextField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_details",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_details",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_name", models.CharField(max_length=200)),
                ("diagnosis_date", models.DateField()),
                ("current_status", models.CharField(max_length=100)),
                ("treatment", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_histories",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(max_length=100)),
                ("morning_before_meal", models.BooleanField(default=False)),
                ("morning_after_meal", models.BooleanField(default=False)),
                ("afternoon_before_meal", models.BooleanField(default=False)),
                ("afternoon_after_meal", models.BooleanField(default=False)),
                ("evening_before_meal", models.BooleanField(default=False)),
                ("evening_after_meal", models.BooleanField(default=False)),
                ("night_before_meal", models.BooleanField(default=False)),
                ("night_after_meal", models.BooleanField(default=False)),
                ("days", models.PositiveIntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicine",
                    ),
                ),
                (
                    "patientHealthDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_details",
                        to="medical_records.patienthealthdetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patienthealthdetails",
            name="medicines",
            field=models.ManyToManyField(
                related_name="medicines",
                through="medical_records.PatientMedicineDetails",
                to="medicines.medicine",
            ),
        ),
        migrations.CreateModel(
            name="PatientSurgicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgery_name", models.CharField(max_length=200)),
                ("surgery_date", models.DateField()),
                ("hospital", models.CharField(max_length=200)),
                ("surgeon", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("complications", models.TextField(blank=True)),
                ("recovery_notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgical_histories",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
    ]
