# Generated by Django 5.1.5 on 2025-02-16 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("appointments", "0002_appointment_doctor"),
        ("medical_records", "0001_initial"),
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHealthDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("allergies", models.TextField(blank=True)),
                ("addictions", models.TextField(blank=True)),
                (
                    "diet",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("VEG", "Vegetarian"),
                            ("NON_VEG", "Non-vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("OTHER", "Other"),
                        ],
                    ),
                ),
                ("sleep_hours", models.DecimalField(decimal_places=1, max_digits=3)),
                ("comorbidities", models.TextField(blank=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=4)),
                ("heart_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("blood_pressure", models.CharField(max_length=20)),
                ("rr", models.DecimalField(decimal_places=2, max_digits=4)),
                ("spo2", models.DecimalField(decimal_places=2, max_digits=4)),
                ("rs", models.CharField(max_length=20)),
                ("cvs", models.CharField(max_length=20)),
                ("p_a", models.CharField(max_length=20)),
                ("cns", models.CharField(max_length=20)),
                ("presenting_complaints", models.TextField(blank=True)),
                ("investigation_advice", models.TextField(blank=True)),
                ("diet_advice", models.TextField(blank=True)),
                ("follow_up_date", models.DateField()),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_details",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_details",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(max_length=100)),
                ("morning_before_meal", models.BooleanField(default=False)),
                ("morning_after_meal", models.BooleanField(default=False)),
                ("afternoon_before_meal", models.BooleanField(default=False)),
                ("afternoon_after_meal", models.BooleanField(default=False)),
                ("evening_before_meal", models.BooleanField(default=False)),
                ("evening_after_meal", models.BooleanField(default=False)),
                ("night_before_meal", models.BooleanField(default=False)),
                ("night_after_meal", models.BooleanField(default=False)),
                ("days", models.PositiveIntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicine",
                    ),
                ),
                (
                    "patientHealthDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_details",
                        to="medical_records.patienthealthdetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patienthealthdetails",
            name="medicines",
            field=models.ManyToManyField(
                related_name="medicines",
                through="medical_records.PatientMedicineDetails",
                to="medicines.medicine",
            ),
        ),
        migrations.DeleteModel(
            name="PatientMedication",
        ),
    ]
