# Generated by Django 5.1.5 on 2025-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0003_alter_patienthealthdetails_blood_pressure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="addictions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="blood_pressure",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="bmi",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="cns",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="comorbidities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="cvs",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="diet",
            field=models.TextField(
                blank=True,
                choices=[
                    ("VEG", "Vegetarian"),
                    ("NON_VEG", "Non-vegetarian"),
                    ("VEGAN", "Vegan"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="diet_advice",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="heart_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="investigation_advice",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="p_a",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="presenting_complaints",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="rr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="rs",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="sleep_hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="spo2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
