# Generated by Django 5.1.5 on 2025-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0004_alter_patienthealthdetails_addictions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="heart_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="rr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="spo2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patienthealthdetails",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
