# docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.Prod
    command: python src/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/mediafiles
    expose:
      - 8001
    environment:
      - DB_ENGINE=postgresql
      - DB_HOST=db
      - DB_NAME=healthcaredatabase
      - DB_USERNAME=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DEBUG=TRUE
      - SECRET_KEY=abcdefghijklmnopqrstuvwxys123456
      - ALLOWED_HOSTS=18.207.2.107,drmakwanaclinic.link
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:

networks:
  app_network:
    external: true